name: ci
on:
  push:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v7
      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go test .
      - name: Run vet
        run: go vet .
      - name: build code
        run: go build .
  build:
    uses: ./.github/workflows/build.yaml
    secrets: 
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets. DOCKER_TOKEN }}
    
        
        
    
