name: security
on:
  workflow_call:
jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: set up go language
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: check directory
        run: |
          pwd
          ls -la
          find . -iname go.mod
      - name: Run vulnerability check
        run: govulncheck ./...
  gosec:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses:  actions/checkout@v4
      - name: set up go environment
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Add go bin to path
        run: echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: check directory
        run: |
          pwd
          ls -la
          find . -iname go.mod
      - name: Run security scan
        run: gosec ./...
