name: security
on:
  push:
    branches: ["master"]
   
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout and download dependencies
        uses: ./.github/workflows/ci.yaml
      - name: install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Run vulnerability check
        run: govulncheck .
      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run security scan
        run: gosec .
